/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppLinkedinRouteImport } from './routes/_app.linkedin'
import { Route as AppInterviewRouteImport } from './routes/_app.interview'
import { Route as AppDemoRouteImport } from './routes/_app.demo'
import { Route as AppAccountRouteImport } from './routes/_app.account'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLinkedinRoute = AppLinkedinRouteImport.update({
  id: '/linkedin',
  path: '/linkedin',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewRoute = AppInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => AppRoute,
} as any)
const AppDemoRoute = AppDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AppAccountRoute
  '/demo': typeof AppDemoRoute
  '/interview': typeof AppInterviewRoute
  '/linkedin': typeof AppLinkedinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AppAccountRoute
  '/demo': typeof AppDemoRoute
  '/interview': typeof AppInterviewRoute
  '/linkedin': typeof AppLinkedinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/account': typeof AppAccountRoute
  '/_app/demo': typeof AppDemoRoute
  '/_app/interview': typeof AppInterviewRoute
  '/_app/linkedin': typeof AppLinkedinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/account' | '/demo' | '/interview' | '/linkedin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/account' | '/demo' | '/interview' | '/linkedin'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/account'
    | '/_app/demo'
    | '/_app/interview'
    | '/_app/linkedin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/linkedin': {
      id: '/_app/linkedin'
      path: '/linkedin'
      fullPath: '/linkedin'
      preLoaderRoute: typeof AppLinkedinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interview': {
      id: '/_app/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof AppInterviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/demo': {
      id: '/_app/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof AppDemoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppDemoRoute: typeof AppDemoRoute
  AppInterviewRoute: typeof AppInterviewRoute
  AppLinkedinRoute: typeof AppLinkedinRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppDemoRoute: AppDemoRoute,
  AppInterviewRoute: AppInterviewRoute,
  AppLinkedinRoute: AppLinkedinRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
